update `pipeline` using the new "activate" convention to activate `subject`
datajoint/workflow-ephys pull request #6
Opened 2020-12-07 16:20 UTC by ttngu207

2020-12-07 16:38 UTC, dimitri-yatsenko commented on workflow_ephys/pipeline.py
>  @lab.schema
Should `SkullReference` be defined in `@schema` rather than `@lab.schema`. It may be cleaner that way.

2021-02-26 19:01 UTC, dimitri-yatsenko requested changes

2021-03-01 16:50 UTC, ttngu207 commented on workflow_ephys/ingest.py
> +        if acq_software is None:
I'm not sure how to modify this, the `for` loop above has to finish for us to determine if `acq_software` is None or not None

2021-03-01 16:52 UTC, ttngu207 commented on workflow_ephys/populate.py
> +    populate_settings = {'display_progress': display_progress, 'reserve_jobs': False, 'suppress_errors': True}
The errors would get printed out on console, depending on how the users would want to orchestrate their workers for this `populate` job, they can modify the settings here (more likely they'll set `reserve_jobs` to `True`)

2021-03-01 21:21 UTC, dimitri-yatsenko commented on workflow_ephys/ingest.py
> +
```suggestion
        for ephys_pattern, ephys_acq_type in zip(['*.ap.meta', '*.oebin'], ['SpikeGLX', 'OpenEphys']):
            ephys_meta_filepaths = [fp for fp in sess_dir.rglob(ephys_pattern)]
            if len(ephys_meta_filepaths):
                acq_software = ephys_acq_type
                break
        else:
            raise FileNotFoundError(f'Ephys recording data not found! Neither SpikeGLX nor OpenEphys recording files found in: {sess_dir}')

```

2021-03-01 21:30 UTC, dimitri-yatsenko commented on workflow_ephys/populate.py
> +    populate_settings = {'display_progress': display_progress, 'reserve_jobs': False, 'suppress_errors': True}
Perhaps the best initial behavior is to throw the errors rather than print them.

2021-03-01 21:34 UTC, dimitri-yatsenko commented on workflow_ephys/ingest.py
> +
```suggestion
else:
     assert False, "invalid value of acq_software"
```

2021-03-07 12:46 UTC, merged